import type { SFTTestDefinition } from '@/src/types/battery.types';

/** Static definitions for the 7 Senior Fitness Test (Rikli & Jones, 2001) */
export const SFT_TESTS: SFTTestDefinition[] = [
    {
        type: 'chair_stand',
        name: 'Sentarse y levantarse de silla',
        shortName: 'Fuerza inferior',
        description:
            'El adulto mayor se sienta y se levanta de la silla el mayor número de veces posible en 30 segundos con los brazos cruzados sobre el pecho.',
        icon: 'human-male',
        unit: 'reps',
        timerMode: 'countdown',
        timerSeconds: 30,
        counterMode: 'increment',
        allowNegative: false,
        inputLabel: 'Repeticiones',
        normativeRanges: {
            belowBelowAvg: 8,
            belowAvg: 12,
            avg: 15,
            aboveAvg: 19,
            excellent: 23,
            higherIsBetter: true,
        },
    },
    {
        type: 'arm_curl',
        name: 'Flexión de codo (Arm Curl)',
        shortName: 'Fuerza superior',
        description:
            'Flexiones de codo con mancuerna (2.27 kg mujeres / 3.63 kg hombres) en 30 segundos, sentado.',
        icon: 'arm-flex',
        unit: 'reps',
        timerMode: 'countdown',
        timerSeconds: 30,
        counterMode: 'increment',
        allowNegative: false,
        inputLabel: 'Repeticiones',
        normativeRanges: {
            belowBelowAvg: 10,
            belowAvg: 13,
            avg: 16,
            aboveAvg: 20,
            excellent: 24,
            higherIsBetter: true,
        },
    },
    {
        type: 'two_min_step',
        name: 'Marcha estacionaria 2 minutos',
        shortName: 'Resistencia (alternativa)',
        description:
            'Elevar las rodillas alternativamente durante 2 minutos. Se cuentan las elevaciones de la rodilla derecha.',
        icon: 'shoe-sneaker',
        unit: 'steps',
        timerMode: 'countdown',
        timerSeconds: 120,
        counterMode: 'increment',
        allowNegative: false,
        inputLabel: 'Pasos (rodilla derecha)',
        normativeRanges: {
            belowBelowAvg: 60,
            belowAvg: 75,
            avg: 90,
            aboveAvg: 110,
            excellent: 130,
            higherIsBetter: true,
        },
    },
    {
        type: 'chair_sit_reach',
        name: 'Sentado y extenderse (Chair Sit-and-Reach)',
        shortName: 'Flexibilidad inferior',
        description:
            'Sentado al borde de la silla, extender una pierna y alcanzar los dedos del pie. Se registra la distancia en cm (negativo si no alcanza).',
        icon: 'yoga',
        unit: 'cm',
        timerMode: 'none',
        counterMode: 'manual_input',
        allowNegative: true,
        inputLabel: 'Distancia (cm, puede ser negativo)',
        normativeRanges: {
            belowBelowAvg: -4,
            belowAvg: -1,
            avg: 2,
            aboveAvg: 5,
            excellent: 8,
            higherIsBetter: true,
        },
    },
    {
        type: 'back_scratch',
        name: 'Rascarse la espalda (Back Scratch)',
        shortName: 'Flexibilidad superior',
        description:
            'Un brazo por encima del hombro y el otro por detrás de la espalda, intentando que los dedos se toquen. Se registra la distancia en cm (negativo si no se tocan).',
        icon: 'human-handsdown',
        unit: 'cm',
        timerMode: 'none',
        counterMode: 'manual_input',
        allowNegative: true,
        inputLabel: 'Distancia (cm, puede ser negativo)',
        normativeRanges: {
            belowBelowAvg: -12,
            belowAvg: -6,
            avg: -1,
            aboveAvg: 4,
            excellent: 8,
            higherIsBetter: true,
        },
    },
    {
        type: 'up_and_go',
        name: '8-Foot Up-and-Go',
        shortName: 'Agilidad y equilibrio',
        description:
            'Levantarse de la silla, caminar 2.44 m, rodear un cono y volver a sentarse. Se mide el tiempo en segundos. Menor tiempo = mejor.',
        icon: 'timer-outline',
        unit: 'seconds',
        timerMode: 'stopwatch',
        counterMode: 'timer_result',
        allowNegative: false,
        inputLabel: 'Tiempo (segundos)',
        normativeRanges: {
            belowBelowAvg: 14,
            belowAvg: 12,
            avg: 10,
            aboveAvg: 8,
            excellent: 6,
            higherIsBetter: false,
        },
    },
    {
        type: 'six_min_walk',
        name: 'Caminata de 6 minutos',
        shortName: 'Resistencia aeróbica',
        description:
            'Recorrer la mayor distancia posible en 6 minutos caminando alrededor de un rectángulo de 45.7 m.',
        icon: 'walk',
        unit: 'meters',
        timerMode: 'countdown',
        timerSeconds: 360,
        counterMode: 'manual_input',
        allowNegative: false,
        inputLabel: 'Metros recorridos',
        encouragementCues: [
            { atSecond: 180, message: 'Quedan 3 minutos. Acelera el paso si puedes.' },
            { atSecond: 60, message: 'Queda 1 minuto. ¡Casi terminamos!' },
        ],
        soundCues: true,
        normativeRanges: {
            belowBelowAvg: 350,
            belowAvg: 450,
            avg: 550,
            aboveAvg: 650,
            excellent: 750,
            higherIsBetter: true,
        },
    },
];

/** Get a specific SFT test definition by type */
export function getSFTTest(type: string): SFTTestDefinition | undefined {
    return SFT_TESTS.find((t) => t.type === type);
}
