import type { SFTTestDefinition } from '@/src/types/battery.types';

/** Static definitions for the 6 Senior Fitness Test (Rikli & Jones, 2001). */
// La caminata de 6 minutos se ocultó de la batería; la marcha de dos minutos cubre la resistencia aeróbica.
export const SFT_TESTS: SFTTestDefinition[] = [
    {
        type: 'chair_stand',
        name: 'Sentarse y levantarse de una silla',
        shortName: 'Fuerza inferior',
        description: 'Evaluar la fuerza del tren inferior mediante sentadillas en silla.',
        icon: 'human-male',
        unit: 'reps',
        timerMode: 'countdown',
        timerSeconds: 30,
        counterMode: 'increment',
        allowNegative: false,
        inputLabel: 'Repeticiones',
        normativeRanges: {
            belowBelowAvg: 8,
            belowAvg: 12,
            avg: 15,
            aboveAvg: 19,
            excellent: 23,
            higherIsBetter: true,
        },
        procedure: [
            '**Posición:** sentado en el medio de la silla, **espalda recta**, pies apoyados en el suelo, **brazos cruzados en el pecho**.',
            'A la señal de "ya", **levantarse completamente** y volver a la posición inicial el mayor número de veces en **30s**.',
            'Demostrar primero **lento** y después **rápido**. El participante puede hacer **1-2 practice reps**.',
            '**Puntuación:** si completa la **mitad o más** del movimiento, cuenta. **Un solo intento**.',
        ],
        safetyTips: [
            '**El respaldo de la silla** debe estar apoyado en la pared o alguien lo sujeta.',
            'Observar si el participante presenta algún **problema de equilibrio**.',
            '**Parar el test inmediatamente** si siente dolor.',
        ],
    },
    {
        type: 'arm_curl',
        name: 'Flexiones del brazo',
        shortName: 'Fuerza superior',
        description: 'Evaluar la fuerza del tren superior con mancuerna (5 libras mujeres / 8 libras hombres).',
        icon: 'arm-flex',
        unit: 'reps',
        timerMode: 'countdown',
        timerSeconds: 30,
        counterMode: 'increment',
        allowNegative: false,
        inputLabel: 'Repeticiones',
        normativeRanges: {
            belowBelowAvg: 10,
            belowAvg: 13,
            avg: 16,
            aboveAvg: 20,
            excellent: 24,
            higherIsBetter: true,
        },
        procedure: [
            '**Posición:** sentado, espalda recta, pies en suelo, **lado dominante** pegado al borde. Peso perpendicular al suelo, palma hacia el cuerpo, **brazo extendido**.',
            'Rotar la muñeca (**supinación**) hasta completar la flexión, palma hacia arriba. Volver con extensión completa. **Mover solo el antebrazo**, **codo pegado al cuerpo**.',
            '**Puntuación:** número total de flexiones en **30s**. Si completa la **mitad o más**, cuenta. **Un solo intento**.',
        ],
        safetyTips: [
            'Verificar que el **peso sea adecuado** (5 libras mujeres / 8 libras hombres).',
            'Asegurar que el **codo permanezca pegado al cuerpo** durante todo el movimiento.',
            '**Parar el test** si el participante siente dolor.',
        ],
    },
    {
        type: 'two_min_step',
        name: 'Marcha de dos minutos',
        shortName: 'Resistencia (alternativa)',
        description: 'Evaluar la resistencia aeróbica marchando en el sitio.',
        icon: 'shoe-sneaker',
        unit: 'steps',
        timerMode: 'countdown',
        timerSeconds: 120,
        counterMode: 'increment',
        allowNegative: false,
        inputLabel: 'Pasos (rodilla derecha)',
        normativeRanges: {
            belowBelowAvg: 60,
            belowAvg: 75,
            avg: 90,
            aboveAvg: 110,
            excellent: 130,
            higherIsBetter: true,
        },
        procedure: [
            '**Preparación:** medir altura de rodilla con **cordón desde cresta ilíaca hasta mitad de la rótula**, doblar por la mitad, marcar en el muslo y transferir a la pared.',
            'A la señal de "ya", **marchar en el sitio** el mayor número de veces posible durante **2 minutos**. Se cuenta la **rodilla derecha**.',
            'Si no alcanza la marca, **reducir el ritmo sin detener el tiempo**. **Un solo intento**. Al finalizar, caminar despacio **1 minuto**.',
        ],
        safetyTips: [
            'Si tiene **problemas de equilibrio**, colocarse cerca de una pared o silla.',
            '**Supervisar** signos de esfuerzo excesivo.',
        ],
    },
    {
        type: 'chair_sit_reach',
        name: 'Flexión del tronco en silla',
        shortName: 'Flexibilidad inferior',
        description: 'Evaluar la flexibilidad del tren inferior (principalmente bíceps femoral).',
        icon: 'yoga',
        unit: 'cm',
        timerMode: 'none',
        counterMode: 'manual_input',
        allowNegative: true,
        inputLabel: 'Distancia entre dedos',
        normativeRanges: {
            belowBelowAvg: -4,
            belowAvg: -1,
            avg: 2,
            aboveAvg: 5,
            excellent: 8,
            higherIsBetter: true,
        },
        procedure: [
            '**Posición:** sentado en el borde de la silla, pliegue pierna-glúteos apoyado en el borde. Una pierna doblada con pie en suelo, otra **extendida recta** enfrente.',
            'Brazos extendidos, manos juntas, **dedos medios**. Flexionar la cadera lentamente intentando alcanzar los dedos del pie. **Mantener 2 segundos**.',
            'Si la pierna se flexiona, **volver a posición inicial** hasta que quede extendida. Probar con **ambas piernas**.',
            '**Puntuación:** **dos intentos** con la pierna preferida, **registrar el mejor**. Tocar punta del zapato = **0**. No alcanzar = **negativo**. Sobrepasar = **positivo**.',
        ],
        safetyTips: [
            '**El respaldo de la silla** debe estar apoyado en la pared.',
            '**Exhalar el aire lentamente** al realizar la flexión.',
            '**Nunca** debe llegar al punto de dolor.',
            'Personas con **osteoporosis severa** no deben realizar el test.',
        ],
    },
    {
        type: 'back_scratch',
        name: 'Juntar las manos tras la espalda',
        shortName: 'Flexibilidad superior',
        description: 'Evaluar la flexibilidad del tren superior (principalmente hombros).',
        icon: 'human-handsdown',
        unit: 'cm',
        timerMode: 'none',
        counterMode: 'manual_input',
        allowNegative: true,
        inputLabel: 'Distancia entre dedos',
        normativeRanges: {
            belowBelowAvg: -12,
            belowAvg: -6,
            avg: -1,
            aboveAvg: 4,
            excellent: 8,
            higherIsBetter: true,
        },
        procedure: [
            '**Posición:** **de pie**. Mano preferida sobre el mismo hombro, palma hacia abajo, dedos extendidos. Llevar la mano hacia la mitad de la espalda, **codo arriba**.',
            'El otro brazo rodeando la cintura con la palma hacia arriba, intentando que se toquen los **dedos medios**. **No cogerse los dedos y tirar**.',
            'Practicar para determinar el mejor lado. **Dos intentos** con el mejor lado, **registrar el mejor**.',
            '**Puntuación:** si los dedos solo se tocan = **0**. No se tocan = **negativo**. Se solapan = **positivo**.',
        ],
        safetyTips: [
            '**Detener el test** si siente dolor.',
            '**Continuar respirando** y evitar movimientos bruscos.',
        ],
    },
    {
        type: 'up_and_go',
        name: 'Levantarse, caminar y volverse a sentar',
        shortName: 'Agilidad y equilibrio',
        description: 'Evaluar la agilidad y el equilibrio dinámico. Menor tiempo = mejor desempeño.',
        icon: 'timer-outline',
        unit: 'seconds',
        timerMode: 'stopwatch',
        counterMode: 'timer_result',
        allowNegative: false,
        inputLabel: 'Tiempo (segundos)',
        normativeRanges: {
            belowBelowAvg: 14,
            belowAvg: 12,
            avg: 10,
            aboveAvg: 8,
            excellent: 6,
            higherIsBetter: false,
        },
        procedure: [
            '**Preparación:** silla pegada a la pared, cono a **2,44 m** desde la parte posterior del cono hasta el borde anterior de la silla.',
            '**Posición:** sentado en el medio, espalda recta, pies en suelo, manos sobre muslos, **un pie adelantado**, **tronco inclinado hacia delante**.',
            'A la señal de "ya", levantarse y caminar **lo más rápido posible** hasta rodear el cono y volver a sentarse. El tiempo **empieza al decir "ya"** y **para al sentarse**.',
            '**Demostración** + 1 práctica. **Dos intentos**, **registrar el mejor**.',
        ],
        safetyTips: [
            'El examinador se colocará **entre el cono y la silla** para ayudar si pierde el equilibrio.',
            'Valorar que el participante **se levante y siente de forma segura**.',
        ],
    },
    // ponytail: la caminata de 6 minutos está oculta de la batería activa.
    // Se conserva el tipo six_min_walk en maps/types para leer datos históricos.
];

/** Get a specific SFT test definition by type */
export function getSFTTest(type: string): SFTTestDefinition | undefined {
    return SFT_TESTS.find((t) => t.type === type);
}
