import type { MD3Theme } from 'react-native-paper';
import {
    MD3DarkTheme,
    MD3LightTheme,
    configureFonts,
} from 'react-native-paper';

const fontConfig = {
    displayLarge: {
        fontFamily: 'Montserrat_800ExtraBold',
        fontSize: 57,
        lineHeight: 64,
        letterSpacing: -0.25,
    },
    displayMedium: {
        fontFamily: 'Montserrat_700Bold',
        fontSize: 45,
        lineHeight: 52,
        letterSpacing: 0,
    },
    displaySmall: {
        fontFamily: 'Montserrat_700Bold',
        fontSize: 36,
        lineHeight: 44,
        letterSpacing: 0,
    },
    headlineLarge: {
        fontFamily: 'Montserrat_700Bold',
        fontSize: 32,
        lineHeight: 40,
        letterSpacing: 0,
    },
    headlineMedium: {
        fontFamily: 'Montserrat_700Bold',
        fontSize: 28,
        lineHeight: 36,
        letterSpacing: 0,
    },
    headlineSmall: {
        fontFamily: 'Montserrat_700Bold',
        fontSize: 24,
        lineHeight: 32,
        letterSpacing: 0,
    },
    titleLarge: {
        fontFamily: 'Montserrat_600SemiBold',
        fontSize: 22,
        lineHeight: 28,
        letterSpacing: 0,
    },
    titleMedium: {
        fontFamily: 'Montserrat_600SemiBold',
        fontSize: 16,
        lineHeight: 24,
        letterSpacing: 0.15,
    },
    titleSmall: {
        fontFamily: 'Montserrat_600SemiBold',
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: 0.1,
    },
    bodyLarge: {
        fontFamily: 'Montserrat_500Medium',
        fontSize: 16,
        lineHeight: 24,
        letterSpacing: 0.5,
    },
    bodyMedium: {
        fontFamily: 'Montserrat_400Regular',
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: 0.25,
    },
    bodySmall: {
        fontFamily: 'Montserrat_400Regular',
        fontSize: 12,
        lineHeight: 16,
        letterSpacing: 0.4,
    },
    labelLarge: {
        fontFamily: 'Montserrat_600SemiBold',
        fontSize: 16,
        lineHeight: 20,
        letterSpacing: 0.1,
    },
    labelMedium: {
        fontFamily: 'Montserrat_500Medium',
        fontSize: 12,
        lineHeight: 16,
        letterSpacing: 0.5,
    },
    labelSmall: {
        fontFamily: 'Montserrat_400Regular',
        fontSize: 11,
        lineHeight: 16,
        letterSpacing: 0.5,
    },
} as const;

export const TybachaTheme: MD3Theme = {
    ...MD3LightTheme,
    fonts: configureFonts({ config: fontConfig }),
    colors: {
        ...MD3LightTheme.colors,
        primary: '#006d77',
        onPrimary: '#FFFFFF',
        primaryContainer: '#b2dfdb',
        onPrimaryContainer: '#004d40',
        secondary: '#4a6364',
        onSecondary: '#FFFFFF',
        secondaryContainer: '#cde8e9',
        onSecondaryContainer: '#051f20',
        tertiary: '#5d7a8f',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#c1e0f4',
        onTertiaryContainer: '#1a3a4f',
        error: '#c62828',
        onError: '#FFFFFF',
        errorContainer: '#fde8e8',
        onErrorContainer: '#8c1d18',
        background: '#f8fafc',
        onBackground: '#1f2937',
        surface: '#fafafa',
        onSurface: '#1f2937',
        surfaceVariant: '#eceff1',
        onSurfaceVariant: '#374151',
        outline: '#94a3b8',
        outlineVariant: '#dde3ea',
        scrim: 'rgba(0,0,0,0.5)',
        inverseSurface: '#121212',
        inverseOnSurface: '#f8fafc',
        inversePrimary: '#80cbc4',
        shadow: 'rgba(0,0,0,0.1)',
        surfaceDisabled: 'rgba(31,41,55,0.12)',
        onSurfaceDisabled: 'rgba(31,41,55,0.38)',
        backdrop: 'rgba(0,0,0,0.4)',
        elevation: {
            level0: 'transparent',
            level1: '#f5f7f9',
            level2: '#f0f3f6',
            level3: '#edf0f4',
            level4: '#eaeef2',
            level5: '#e7ebf0',
        },
    },
    roundness: 4,
};

export const TybachaDarkTheme: MD3Theme = {
    ...MD3DarkTheme,
    fonts: configureFonts({ config: fontConfig }),
    colors: {
        ...MD3DarkTheme.colors,
        primary: '#80cbc4',
        onPrimary: '#003730',
        primaryContainer: '#004d40',
        onPrimaryContainer: '#b2dfdb',
        secondary: '#b1cccd',
        onSecondary: '#1c3435',
        secondaryContainer: '#334b4c',
        onSecondaryContainer: '#cde8e9',
        tertiary: '#a5c4d8',
        onTertiary: '#0b2e43',
        tertiaryContainer: '#24455a',
        onTertiaryContainer: '#c1e0f4',
        error: '#ffb4ab',
        onError: '#690005',
        errorContainer: '#93000a',
        onErrorContainer: '#ffdad6',
        background: '#121212',
        onBackground: '#e2e2e6',
        surface: '#1e2a2b',
        onSurface: '#e2e2e6',
        surfaceVariant: '#2c3a3b',
        onSurfaceVariant: '#bec8ca',
        outline: '#899294',
        outlineVariant: '#3f4e4f',
        scrim: 'rgba(0,0,0,0.7)',
        inverseSurface: '#e2e2e6',
        inverseOnSurface: '#2f3131',
        inversePrimary: '#006d77',
        shadow: 'rgba(0,0,0,0.3)',
        surfaceDisabled: 'rgba(226,226,230,0.12)',
        onSurfaceDisabled: 'rgba(226,226,230,0.38)',
        backdrop: 'rgba(0,0,0,0.6)',
        elevation: {
            level0: 'transparent',
            level1: '#1e2a2b',
            level2: '#233032',
            level3: '#273638',
            level4: '#2b3c3e',
            level5: '#304244',
        },
    },
    roundness: 4,
};

/** Spacing constants for consistent UI */
export const spacing = {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
} as const;

/** Border radius constants */
export const borderRadius = {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
} as const;
